import { Inter } from "next/font/google";
import "./globals.css";
import './HomePage.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{height:'100vh'}}>
      <body className={inter.className} style={{height:'100vh'}}>{children}</body>
    </html>
  );
}
